PROJECT  = Crypt2
GIT_URL  = git@github.com:timlau/crypt.git

# exclude submodules from source tarball
# GIT_EXCLUDE = 

# Checkout a give git tag
# GIT_TAG = v$(VERSION)

# # Checkout a given git branch
GIT_BRANCH = build-fedora

# Skip ckecking out submodules
# SKIP_SUBMODULES = true

# Mock repository for building RPMs with prebuild JUCE
# MOCK_REPO = https://download.copr.fedorainfracloud.org/results/timlau/audio/fedora-43-x86_64/

ROOT = ../../common
include $(ROOT)/Makefile.git.mk
