PROJECT  = {{ name }}
GIT_URL  = git@github.com:{{ github_owner }}/{{ github_project }}.git

# exclude submodules from source tarball
# GITSUBMODULE_EXCLUDE = 

# Checkout a give git tag
# GIT_TAG = v$(VERSION)

ROOT = ../../common
include $(ROOT)/Makefile.git.mk

