PROJECT  = {{ name }}
GIT_URL  = git@github.com:{{ github_owner }}/{{ github_project }}.git

# exclude submodules from source tarball
# GIT_EXCLUDE = 

# Checkout a give git tag
# GIT_TAG = v$(VERSION)

# # Checkout a given git branch
# GIT_BRANCH = fedora_build

# Skip ckecking out submodules
# SKIP_SUBMODULES = true

# Mock repository for building RPMs with prebuild JUCE
# MOCK_REPO = https://download.copr.fedorainfracloud.org/results/timlau/audio/fedora-43-x86_64/

ROOT = ../../common
include $(ROOT)/Makefile.git.mk

