PROJECT  = OB-Xf
GIT_URL  = git@github.com:surge-synthesizer/OB-Xf.git

# exclude submodules from source tarball
# GIT_EXCLUDE = 

# Checkout a give git tag
# GIT_TAG = v$(VERSION)

ROOT = ../../common
include $(ROOT)/Makefile.git.mk
