PROJECT  = odin2
GIT_URL  = git@github.com:TheWaveWarden/odin2.git

# exclude submodules from source tarball
GITSUBMODULE_EXCLUDE = libs/JUCE libs/JUCELV2

GITSUB_REMOTE = libs/clap-juce-extensions
# Checkout a give git tag
# GIT_TAG = v$(VERSION)

ROOT = ../../common
include $(ROOT)/Makefile.git.mk
