PROJECT  = odin2
GIT_URL  = git@github.com:TheWaveWarden/odin2.git

# exclude submodules from source tarball
#GIT_EXCLUDE = libs/JUCE libs/JUCELV2 libs/clap-juce-extensions

# GITSUB_REMOTE = libs/clap-juce-extensions
# Checkout a give git tag
# GIT_TAG = v$(VERSION)

MOCK_REPO = https://download.copr.fedorainfracloud.org/results/timlau/audio/fedora-43-x86_64/

ROOT = ../../common
include $(ROOT)/Makefile.git.mk
