PROJECT  = odin2
GIT_URL  = git@github.com:timlau/odin2.git
GIT_BRANCH = fedora_build
SKIP_SUBMODULES = true

MOCK_REPO = https://download.copr.fedorainfracloud.org/results/timlau/audio/fedora-43-x86_64/

ROOT = ../../common
include $(ROOT)/Makefile.git.mk
