PROJECT  = clap-juce-extensions
GIT_URL  = git@github.com:free-audio/clap-juce-extensions.git

# exclude submodules from source tarball
# GIT_EXCLUDE = 

# Checkout a give git tag
# GIT_TAG = v$(VERSION)

ROOT = ../../common
include $(ROOT)/Makefile.git.mk
