PROJECT  = ykchorus
GIT_URL  = git@github.com:SpotlightKid/ykchorus.git

# exclude submodules from source tarball
# GITSUBMODULE_EXCLUDE = 

# Checkout a give git tag
# GIT_TAG = v$(VERSION)

ROOT = ../../common
include $(ROOT)/Makefile.git.mk

