PROJECT = dexed
GIT_URL = git@github.com:asb2m10/dexed.git  
# exclude JUCE submodule from source tarball
GIT_EXCLUDE = libs/JUCE
# checkout git tagged version
GIT_TAG = v$(VERSION)

MOCK_REPO = https://download.copr.fedorainfracloud.org/results/timlau/audio/fedora-43-x86_64/

ROOT = ../../common
include $(ROOT)/Makefile.git.mk

